name: Deploy C++ packages

on:
  push:
    paths:
      - conda-recipes/veloxchem/*
      - .github/workflows/deploy-cxx.yml
  pull_request:
    paths:
      - conda-recipes/veloxchem/*
      - .github/workflows/deploy-cxx.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        mpi: [msmpi, mpich, openmpi]
        python: [3.6, 3.7, 3.8, 3.9]
        recipes: [veloxchem]
        exclude:
          - os: macos-latest
            mpi: msmpi
            recipes: veloxchem
          - os: ubuntu-latest
            mpi: msmpi
            recipes: veloxchem
          - os: windows-latest
            mpi: mpich
            recipes: veloxchem
          - os: windows-latest
            mpi: openmpi
            recipes: veloxchem
            
    steps:
      - uses: actions/checkout@v2

      - name: Install macOS SDK
        if: contains(matrix.os, 'macos')
        working-directory: /Users/runner
        run: |
          curl -fsSL https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.9.sdk.tar.xz > ~/MacOSX10.9.sdk.tar.xz
          tar -xzf ~/MacOSX10.9.sdk.tar.xz
          rm ~/MacOSX10.9.sdk.tar.xz
      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0  # Increase this value to reset cache if .github/deploy.yml has not changed
        with:
          path: ~/conda_pkgs_dir
          key:
            cxx-deps-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/deploy.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: deploy
          channels: conda-forge,defaults
          environment-file: .github/deploy.yml
          channel-priority: true
          python-version: 3.8
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

      - name: Build and upload ${{ matrix.recipes }} for triplet ${{ matrix.os }}, Python ${{ matrix.python }}, and ${{ matrix.mpi }}
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/conda-recipes
          conda build ${{ matrix.recipes }} \ 
                -c conda-forge \ 
                --user veloxchem --token $ANACONDA_TOKEN --label main \ 
                --verify \
                --variants "{'python': ['${{ matrix.python }}'], 'mpi': ['${{ matrix.mpi }}']}"
          
      - name: Build and upload ${{ matrix.recipes }} for triplet windows-latest, Python ${{ matrix.python }}, and msmpi
        if: contains(matrix.os, 'windows')
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/conda-recipes
          conda build ${{ matrix.recipes }} \ 
                -c conda-forge \ 
                --user veloxchem --token $ANACONDA_TOKEN --label main \ 
                --verify \
                --variants "{'python': ['${{ matrix.python }}']}"
