name: Deploy C++ packages

on:
  workflow_dispatch:
    sha256:
      description: 'The SHA256 of the package'
      required: true
  push:
    paths:
      - conda-recipes/*
      - .github/workflows/deploy-cxx.yml
  pull_request:
    paths:
      - conda-recipes/*
      - .github/workflows/deploy-cxx.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  #, macos-latest, windows-latest]
        python: [3.6]  #, 3.7, 3.8, 3.9]
            
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0  # Increase this value to reset cache if .github/deploy.yml has not changed
        with:
          path: ~/conda_pkgs_dir
          key:
            cxx-deps-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/deploy.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: deploy
          channels: conda-forge,defaults
          environment-file: .github/deploy.yml
          channel-priority: true
          python-version: 3.8
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

      - name: Build and upload ${{ matrix.recipes }} for ${{ matrix.os }} and Python ${{ matrix.python }}
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          echo "The package sha256 is: ${{ github.event.inputs.sha256 }}!"
          cd $GITHUB_WORKSPACE/conda-recipes
          conda build ${{ matrix.recipes }} \ 
                -c conda-forge \ 
                --user robertodr --token $ANACONDA_TOKEN --label main \ 
                --verify \
                --variants "{'python': ['${{ matrix.python }}']}"
